

// RegisterJobAction = sp.TRecord( script = sp.TBytes,
// allowedSources = sp.TOption(sp.TSet(sp.TString)),
// allowOnlyVerifiedSources = sp.TBool,
// schedule = sp.TRecord( duration = sp.TNat,
// startTime = sp.TNat,
// endTime = sp.TNat,
// interval = sp.TNat,
// maxStartDelay = sp.TNat,
// ),
// memory = sp.TNat,
// networkRequests = sp.TNat,
// storage = sp.TNat,
// extra = sp.TRecord( destination = sp.TBytes,
// parameters = sp.TOption(sp.TBytes),
// requirements = sp.TRecord( slots = sp.TNat,
// reward = sp.TBytes,
// minReputation = sp.TOption(sp.TNat),
// instantMatch = sp.TOption(sp.TSet(sp.TRecord(source = sp.TString,
// startDelay = sp.TNat))),
// ),
// expectedFulfillmentFee = sp.TNat,
// ) )